version: '3'
services: 
    docker-mysql:
        restart: always
        container_name: docker-mysql
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: Efsios#@469
            MYSQL_DATABASE: software
            MYSQL_USER: johnnyho
            MYSQL_PASSWORD: Efsios#@469
        volumes:
            - ./init.sql:/data/application/init.sql
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 2s
            timeout: 20s
            retries: 10
    final-app:
        restart: on-failure
        build: ./
        expose:
            - "8888"
        ports:
            - 8888:8888
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - docker-mysql